[package]
name = "prioritything"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_obj = "0.16.1"
rand = "0.9.2"
windows = { version = "0.62.0", features = ["Win32_System_Threading"] }
